/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/atomOneTheme.ts
 * Command: astryx theme build src/theme/atomOneTheme.ts --out src/theme/theme.css
 * Generated: 2026-07-30T21:13:05.783Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const atomOneIconRegistry: IconRegistry;
export declare const atomOneTheme: DefinedTheme;
