/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/atomOneTheme.ts
 * Command: astryx theme build src/theme/atomOneTheme.ts --out src/theme/theme.css
 * Generated: 2026-07-30T21:13:05.785Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
