/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/flexokiTheme.ts
 * Command: astryx theme build src/theme/flexokiTheme.ts --out src/theme/theme.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

import { flexokiIconRegistry } from './icons';
/**
 * flexoki theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { flexokiTheme } from './flexoki';
 *   import './flexoki.css';
 */
export const flexokiTheme = {
  name: 'flexoki',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-bold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-bold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-bold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-bold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "Libron, Georgia, \"Times New Roman\", Times, serif",
    "--font-family-heading": "\"TeX Gyre Adventor\", \"Century Gothic\", system-ui, sans-serif",
    "--font-family-code": "ui-monospace, \"SF Mono\", SFMono-Regular, Menlo, Monaco, Consolas, \"DejaVu Sans Mono\", monospace",
    "--color-syntax-keyword": "light-dark(#66800B, #879A39)",
    "--color-syntax-string": "light-dark(#24837B, #3AA99F)",
    "--color-syntax-comment": "light-dark(#B7B5AC, #575653)",
    "--color-syntax-number": "light-dark(#5E409D, #8B7EC8)",
    "--color-syntax-function": "light-dark(#BC5215, #DA702C)",
    "--color-syntax-type": "light-dark(#AD8301, #D0A215)",
    "--color-syntax-variable": "light-dark(#205EA6, #4385BE)",
    "--color-syntax-operator": "light-dark(#6F6E69, #878580)",
    "--color-syntax-constant": "light-dark(#AD8301, #D0A215)",
    "--color-syntax-tag": "light-dark(#205EA6, #4385BE)",
    "--color-syntax-attribute": "light-dark(#AD8301, #D0A215)",
    "--color-syntax-property": "light-dark(#205EA6, #4385BE)",
    "--color-syntax-punctuation": "light-dark(#6F6E69, #878580)",
    "--color-syntax-background": "light-dark(#FFFCF0, #100F0F)",
    "--color-accent": "light-dark(#205EA6, #66A0C8)",
    "--color-accent-muted": "light-dark(#205EA614, #66A0C820)",
    "--color-neutral": "light-dark(#100F0F0F, #CECDC31A)",
    "--color-background-surface": "light-dark(#FFFCF0, #1C1B1A)",
    "--color-background-body": "light-dark(#FFFCF0, #100F0F)",
    "--color-overlay": "light-dark(#100F0F80, #100F0FCC)",
    "--color-overlay-hover": "light-dark(#100F0F0D, #CECDC30D)",
    "--color-overlay-pressed": "light-dark(#100F0F1A, #CECDC31A)",
    "--color-background-muted": "light-dark(#F2F0E5, #1C1B1A)",
    "--color-text-primary": "light-dark(#100F0F, #CECDC3)",
    "--color-text-secondary": "light-dark(#6F6E69, #878580)",
    "--color-text-disabled": "light-dark(#B7B5AC, #575653)",
    "--color-text-accent": "light-dark(#205EA6, #66A0C8)",
    "--color-on-dark": "#FFFCF0",
    "--color-on-light": "#100F0F",
    "--color-on-accent": "light-dark(#FFFCF0, #100F0F)",
    "--color-on-success": "light-dark(#FFFCF0, #100F0F)",
    "--color-on-error": "light-dark(#FFFCF0, #100F0F)",
    "--color-on-warning": "light-dark(#100F0F, #100F0F)",
    "--color-icon-accent": "light-dark(#205EA6, #66A0C8)",
    "--color-icon-primary": "light-dark(#100F0F, #CECDC3)",
    "--color-icon-secondary": "light-dark(#6F6E69, #878580)",
    "--color-icon-disabled": "light-dark(#B7B5AC, #575653)",
    "--color-background-card": "light-dark(#FFFCF0, #1C1B1A)",
    "--color-background-popover": "light-dark(#FFFCF0, #1C1B1A)",
    "--color-background-inverted": "light-dark(#100F0F, #CECDC3)",
    "--color-success": "light-dark(#66800B, #879A39)",
    "--color-success-muted": "light-dark(#66800B20, #879A3920)",
    "--color-error": "light-dark(#AF3029, #D14D41)",
    "--color-error-muted": "light-dark(#AF302920, #D14D4120)",
    "--color-warning": "light-dark(#AD8301, #D0A215)",
    "--color-warning-muted": "light-dark(#AD830120, #D0A21520)",
    "--color-border": "light-dark(#DAD8CE, #343331)",
    "--color-border-emphasized": "light-dark(#CECDC3, #403E3C)",
    "--color-skeleton": "light-dark(#E6E4D9, #282726)",
    "--color-shadow": "light-dark(#100F0F1A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#205EA633, #4385BE33)",
    "--color-border-blue": "light-dark(#205EA6, #4385BE)",
    "--color-icon-blue": "light-dark(#205EA6, #4385BE)",
    "--color-text-blue": "light-dark(#1A4F8C, #66A0C8)",
    "--color-background-cyan": "light-dark(#24837B33, #3AA99F33)",
    "--color-border-cyan": "light-dark(#24837B, #3AA99F)",
    "--color-icon-cyan": "light-dark(#24837B, #3AA99F)",
    "--color-text-cyan": "light-dark(#1C6C66, #5ABDAC)",
    "--color-background-green": "light-dark(#66800B33, #879A3933)",
    "--color-border-green": "light-dark(#66800B, #879A39)",
    "--color-icon-green": "light-dark(#66800B, #879A39)",
    "--color-text-green": "light-dark(#536907, #A0AF54)",
    "--color-background-orange": "light-dark(#BC521533, #DA702C33)",
    "--color-border-orange": "light-dark(#BC5215, #DA702C)",
    "--color-icon-orange": "light-dark(#BC5215, #DA702C)",
    "--color-text-orange": "light-dark(#9D4310, #EC8B49)",
    "--color-background-pink": "light-dark(#A02F6F33, #CE5D9733)",
    "--color-border-pink": "light-dark(#A02F6F, #CE5D97)",
    "--color-icon-pink": "light-dark(#A02F6F, #CE5D97)",
    "--color-text-pink": "light-dark(#87285E, #E47DA8)",
    "--color-background-purple": "light-dark(#5E409D33, #8B7EC833)",
    "--color-border-purple": "light-dark(#5E409D, #8B7EC8)",
    "--color-icon-purple": "light-dark(#5E409D, #8B7EC8)",
    "--color-text-purple": "light-dark(#4F3685, #A699D0)",
    "--color-background-red": "light-dark(#AF302933, #D14D4133)",
    "--color-border-red": "light-dark(#AF3029, #D14D41)",
    "--color-icon-red": "light-dark(#AF3029, #D14D41)",
    "--color-text-red": "light-dark(#942822, #E8705F)",
    "--color-background-teal": "light-dark(#24837B33, #3AA99F33)",
    "--color-border-teal": "light-dark(#24837B, #3AA99F)",
    "--color-icon-teal": "light-dark(#24837B, #3AA99F)",
    "--color-text-teal": "light-dark(#1C6C66, #5ABDAC)",
    "--color-background-yellow": "light-dark(#AD830133, #D0A21533)",
    "--color-border-yellow": "light-dark(#AD8301, #D0A215)",
    "--color-icon-yellow": "light-dark(#AD8301, #D0A215)",
    "--color-text-yellow": "light-dark(#8E6B01, #DFB431)",
    "--color-background-gray": "light-dark(#6F6E6933, #87858033)",
    "--color-border-gray": "light-dark(#B7B5AC, #575653)",
    "--color-icon-gray": "light-dark(#6F6E69, #878580)",
    "--color-text-gray": "light-dark(#100F0F, #CECDC3)",
    "--radius-none": "0",
    "--radius-inner": "0",
    "--radius-element": "0",
    "--radius-container": "0",
    "--radius-page": "0",
    "--radius-full": "0",
    "--shadow-low": "0 2px 4px #100F0F0D, 0 4px 8px #100F0F1A",
    "--shadow-med": "0 2px 4px #100F0F0D, 0 4px 12px #100F0F1A",
    "--shadow-high": "0 4px 6px #100F0F1A, 0 12px 24px #100F0F26",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #205EA630",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #205EA650",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #66800B50",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #AD830150",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #AF302950"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "0"
      },
      "variant:secondary": {
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  __adaptations: {
    "widthBreakpoints": {
      "sm": 640,
      "md": 768,
      "lg": 1024,
      "xl": 1280,
      "2xl": 1536
    },
    "rules": []
  },
  __axes: {
    "typography": {
      "scale": {
        "base": 14,
        "ratio": 1.2
      },
      "body": {
        "family": "Libron",
        "fallbacks": "Georgia, \"Times New Roman\", Times, serif"
      },
      "heading": {
        "family": "TeX Gyre Adventor",
        "fallbacks": "\"Century Gothic\", system-ui, sans-serif",
        "weight": "bold"
      },
      "code": {
        "family": "ui-monospace",
        "fallbacks": "\"SF Mono\", SFMono-Regular, Menlo, Monaco, Consolas, \"DejaVu Sans Mono\", monospace"
      }
    },
    "motion": {
      "fast": 125,
      "medium": 300,
      "slow": 700,
      "ratio": 0.75
    }
  },
  icons: flexokiIconRegistry,
};

export { flexokiIconRegistry };
