<script lang="ts">
    import { Modal, Tag } from "carbon-components-svelte";
    import { onMount, tick } from "svelte";
    // JSON is generated by the build step
    // @ts-ignore – Vite will inline JSON
    import resumeData from "../content/resume.json";
  
    type Resume = {
      name: string;
      title?: string;
      contact: { email?: string; phone?: string; location?: string; links?: string[] };
      sections: Array<{ heading: string; items: string[] }>;
      skills?: string[];
    };
  
    let resume: Resume = resumeData;
    export let isOpen = false;
    let scrollProgress = 0;
  
    const MODAL_SEL = ".cds--modal, .bx--modal";
    const CONTAINER_SEL = ".cds--modal-container, .bx--modal-container";
  
    async function syncModalTheme() {
      if (typeof document === "undefined") return;
      await tick();
      const modal = document.querySelector(MODAL_SEL) as HTMLElement | null;
      const container = document.querySelector(CONTAINER_SEL) as HTMLElement | null;
      if (!modal || !container) return;
  
      const currentTheme = document.documentElement.getAttribute("data-carbon-theme") || "g100";
      [modal, container].forEach((el) => el.setAttribute("data-carbon-theme", currentTheme));
  
      const computed = getComputedStyle(document.documentElement);
      for (const name of Array.from(computed)) {
        if (name.startsWith("--cds-")) {
          const value = computed.getPropertyValue(name);
          modal.style.setProperty(name, value);
          container.style.setProperty(name, value);
        }
      }
    }
    $: if (isOpen) syncModalTheme();
  
    function handleHashChange() {
      isOpen = window.location.hash === "#resume-modal";
    }
    function handleClose() {
      isOpen = false;
      if (window.location.hash === "#resume-modal") {
        history.replaceState("", document.title, location.pathname + location.search);
      }
    }
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape" && isOpen) handleClose();
    }
    function handleScroll(e: Event) {
      const t = e.target as HTMLElement;
      const h = t.scrollHeight - t.clientHeight;
      scrollProgress = h > 0 ? (t.scrollTop / h) * 100 : 0;
    }
  
    onMount(() => {
      handleHashChange();
      window.addEventListener("hashchange", handleHashChange);
      window.addEventListener("keydown", handleKeyDown);
  
      const observer = new MutationObserver((m) => {
        if (m.some(x => x.type === "attributes" && x.attributeName === "data-carbon-theme")) {
          if (isOpen) syncModalTheme();
        }
      });
      observer.observe(document.documentElement, { attributes: true, attributeFilter: ["data-carbon-theme"] });
  
      return () => {
        window.removeEventListener("hashchange", handleHashChange);
        window.removeEventListener("keydown", handleKeyDown);
        observer.disconnect();
      };
    });
  </script>
  
  <Modal
    bind:open={isOpen}
    size="lg"
    passiveModal={true}
    on:close={handleClose}
    class="carbon-resume-modal"
  >
    <h3 slot="heading" class="modal-heading-with-progress">
      {resume?.name}{resume?.title ? ` — ${resume.title}` : ''}
      <div class="header-progress" aria-hidden="true">
        <div class="header-progress-bar" style="width: {scrollProgress}%"></div>
      </div>
      <span class="visually-hidden" role="status" aria-live="polite">
        {Math.round(scrollProgress)}% scrolled
      </span>
    </h3>
  
    <div class="modal-content" on:scroll={handleScroll}>
      {#if resume}
        <section class="summary">
          <div class="grid">
            {#if resume.contact.email}<div><strong>Email:</strong> {resume.contact.email}</div>{/if}
            {#if resume.contact.phone}<div><strong>Phone:</strong> {resume.contact.phone}</div>{/if}
            {#if resume.contact.location}<div><strong>Location:</strong> {resume.contact.location}</div>{/if}
            {#if resume.contact.links?.length}
              <div class="links"><strong>Links:</strong>
                {#each resume.contact.links as link}
                  <a href={link} target="_blank" rel="noopener noreferrer">{link}</a>
                {/each}
              </div>
            {/if}
          </div>
          {#if resume.skills?.length}
            <div class="skills">
              {#each resume.skills as s}
                <Tag type="outline" size="sm">{s}</Tag>
              {/each}
            </div>
          {/if}
        </section>
  
        {#each resume.sections as sec}
          <h4 class="cds--type-productive-heading-02">{sec.heading}</h4>
          <ul>
            {#each sec.items as item}
              <li>{item}</li>
            {/each}
          </ul>
        {/each}
      {/if}
    </div>
  </Modal>
  
  <style>
    :global(.cds--modal-container){ max-width: 1100px; width:100%; height: 90vh; max-height: 90vh; }
    :global(.cds--modal-content){ padding:0; height:100%; display:flex; flex-direction:column; }
    :global(.cds--modal-header){ position:relative; padding: var(--cds-spacing-05); border-bottom: 1px solid var(--cds-border-subtle); }
  
    .modal-heading-with-progress { position:relative; margin:0; padding-bottom: calc(var(--cds-spacing-05) - 4px); }
    .header-progress { position:absolute; left:0; right:0; bottom:-1px; height:4px; background: var(--cds-layer-accent); overflow:hidden; }
    .header-progress-bar { height:100%; background: linear-gradient(90deg, var(--cds-interactive), var(--cds-focus)); transition: width .1s ease; }
    .visually-hidden { position:absolute!important; clip:rect(1px,1px,1px,1px); clip-path: inset(50%); height:1px; overflow:hidden; white-space:nowrap; width:1px; }
  
    .modal-content { position:relative; flex:1; overflow-y:auto; -webkit-overflow-scrolling:touch; scroll-behavior:smooth; padding: var(--cds-spacing-05); }
    .summary .grid { display:grid; gap:.25rem; margin-bottom: .75rem; }
    .summary .links a { margin-right:.5rem; }
    .skills { display:flex; flex-wrap:wrap; gap:.25rem; margin: .25rem 0 1rem; }
  
    ul { margin-left: 1.25rem; }
    li { margin-bottom:.375rem; }
  </style>
  