export type TechIcon = {
    iconClass: string;
    label: string;
    category?: 'language' | 'framework' | 'tool' | 'database' | 'cloud' | 'other';
};

export const TECH_STACK: Record<string, TechIcon> = {
    // --- Languages ---
    JavaScript: { iconClass: "fab fa-js-square", label: "JavaScript", category: "language" },
    TypeScript: { iconClass: "fab fa-js-square", label: "TypeScript", category: "language" },
    Python: { iconClass: "fab fa-python", label: "Python", category: "language" },
    Java: { iconClass: "fab fa-java", label: "Java", category: "language" },
    Dart: { iconClass: "fas fa-gem", label: "Dart", category: "language" },
    Lua: { iconClass: "fas fa-moon", label: "Lua", category: "language" },
    SQL: { iconClass: "fas fa-database", label: "SQL", category: "language" },
    "HTML/CSS": { iconClass: "fab fa-html5", label: "HTML/CSS", category: "language" },
    HTML: { iconClass: "fab fa-html5", label: "HTML", category: "language" },
    CSS: { iconClass: "fab fa-css3-alt", label: "CSS", category: "language" },
    "C#": { iconClass: "fab fa-cuttlefish", label: "C#", category: "language" },
    "C++": { iconClass: "fas fa-code", label: "C++", category: "language" },
    C: { iconClass: "fas fa-code", label: "C", category: "language" },
    Go: { iconClass: "fab fa-golang", label: "Go", category: "language" },
    Rust: { iconClass: "fab fa-rust", label: "Rust", category: "language" },
    PHP: { iconClass: "fab fa-php", label: "PHP", category: "language" },
    Swift: { iconClass: "fab fa-swift", label: "Swift", category: "language" },
    Kotlin: { iconClass: "fab fa-kickstarter-k", label: "Kotlin", category: "language" },
    Ruby: { iconClass: "fas fa-gem", label: "Ruby", category: "language" },
    Scala: { iconClass: "fas fa-code", label: "Scala", category: "language" },
    R: { iconClass: "fas fa-chart-line", label: "R", category: "language" },
    MATLAB: { iconClass: "fas fa-calculator", label: "MATLAB", category: "language" },

    // --- Frontend Frameworks & Libraries ---
    React: { iconClass: "fab fa-react", label: "React", category: "framework" },
    "React Native": { iconClass: "fab fa-react", label: "React Native", category: "framework" },
    "Next.js": { iconClass: "fab fa-react", label: "Next.js", category: "framework" },
    Vue: { iconClass: "fab fa-vuejs", label: "Vue", category: "framework" },
    "Vue.js": { iconClass: "fab fa-vuejs", label: "Vue.js", category: "framework" },
    "Nuxt.js": { iconClass: "fab fa-vuejs", label: "Nuxt.js", category: "framework" },
    Angular: { iconClass: "fab fa-angular", label: "Angular", category: "framework" },
    Svelte: { iconClass: "fas fa-fan", label: "Svelte", category: "framework" },
    SvelteKit: { iconClass: "fas fa-fan", label: "SvelteKit", category: "framework" },
    Astro: { iconClass: "fas fa-rocket", label: "Astro", category: "framework" },
    Gatsby: { iconClass: "fab fa-react", label: "Gatsby", category: "framework" },
    Remix: { iconClass: "fab fa-react", label: "Remix", category: "framework" },
    "Solid.js": { iconClass: "fas fa-cube", label: "Solid.js", category: "framework" },
    Preact: { iconClass: "fab fa-react", label: "Preact", category: "framework" },
    "Alpine.js": { iconClass: "fas fa-mountain", label: "Alpine.js", category: "framework" },
    Lit: { iconClass: "fas fa-fire", label: "Lit", category: "framework" },
    Stencil: { iconClass: "fas fa-atom", label: "Stencil", category: "framework" },

    // --- CSS Frameworks & Styling ---
    "Tailwind CSS": { iconClass: "fas fa-wind", label: "Tailwind CSS", category: "tool" },
    Bootstrap: { iconClass: "fab fa-bootstrap", label: "Bootstrap", category: "tool" },
    Bulma: { iconClass: "fas fa-columns", label: "Bulma", category: "tool" },
    "Material-UI": { iconClass: "fas fa-palette", label: "Material-UI", category: "tool" },
    "Ant Design": { iconClass: "fas fa-ant", label: "Ant Design", category: "tool" },
    "Chakra UI": { iconClass: "fas fa-circle", label: "Chakra UI", category: "tool" },
    "Styled Components": { iconClass: "fas fa-paint-brush", label: "Styled Components", category: "tool" },
    Emotion: { iconClass: "fas fa-smile", label: "Emotion", category: "tool" },
    SASS: { iconClass: "fab fa-sass", label: "SASS", category: "tool" },
    SCSS: { iconClass: "fab fa-sass", label: "SCSS", category: "tool" },
    Less: { iconClass: "fas fa-minus", label: "Less", category: "tool" },
    PostCSS: { iconClass: "fas fa-mail-forward", label: "PostCSS", category: "tool" },

    // --- Mobile Development ---
    Expo: { iconClass: "fas fa-mobile-alt", label: "Expo", category: "framework" },
    Flutter: { iconClass: "fas fa-mobile-alt", label: "Flutter", category: "framework" },
    Ionic: { iconClass: "fas fa-mobile-alt", label: "Ionic", category: "framework" },
    Xamarin: { iconClass: "fab fa-microsoft", label: "Xamarin", category: "framework" },
    Cordova: { iconClass: "fas fa-mobile-alt", label: "Cordova", category: "framework" },
    PhoneGap: { iconClass: "fas fa-mobile-alt", label: "PhoneGap", category: "framework" },
    NativeScript: { iconClass: "fas fa-mobile-alt", label: "NativeScript", category: "framework" },

    // --- Backend Frameworks & Runtimes ---
    "Node.js": { iconClass: "fab fa-node-js", label: "Node.js", category: "framework" },
    "Express.js": { iconClass: "fas fa-server", label: "Express.js", category: "framework" },
    Fastify: { iconClass: "fas fa-bolt", label: "Fastify", category: "framework" },
    "Koa.js": { iconClass: "fas fa-server", label: "Koa.js", category: "framework" },
    NestJS: { iconClass: "fas fa-cat", label: "NestJS", category: "framework" },
    Django: { iconClass: "fab fa-python", label: "Django", category: "framework" },
    Flask: { iconClass: "fab fa-python", label: "Flask", category: "framework" },
    FastAPI: { iconClass: "fas fa-rocket", label: "FastAPI", category: "framework" },
    "Spring Boot": { iconClass: "fab fa-java", label: "Spring Boot", category: "framework" },
    Spring: { iconClass: "fab fa-java", label: "Spring", category: "framework" },
    "Ruby on Rails": { iconClass: "fas fa-gem", label: "Ruby on Rails", category: "framework" },
    Laravel: { iconClass: "fab fa-php", label: "Laravel", category: "framework" },
    Symfony: { iconClass: "fab fa-php", label: "Symfony", category: "framework" },
    "ASP.NET": { iconClass: "fab fa-microsoft", label: "ASP.NET", category: "framework" },
    ".NET": { iconClass: "fab fa-microsoft", label: ".NET", category: "framework" },
    Gin: { iconClass: "fab fa-golang", label: "Gin", category: "framework" },
    Echo: { iconClass: "fab fa-golang", label: "Echo", category: "framework" },
    Actix: { iconClass: "fab fa-rust", label: "Actix", category: "framework" },
    Rocket: { iconClass: "fab fa-rust", label: "Rocket", category: "framework" },

    // --- Databases & Storage ---
    PostgreSQL: { iconClass: "fas fa-database", label: "PostgreSQL", category: "database" },
    MySQL: { iconClass: "fas fa-database", label: "MySQL", category: "database" },
    MongoDB: { iconClass: "fas fa-leaf", label: "MongoDB", category: "database" },
    Redis: { iconClass: "fas fa-database", label: "Redis", category: "database" },
    SQLite: { iconClass: "fas fa-database", label: "SQLite", category: "database" },
    MariaDB: { iconClass: "fas fa-database", label: "MariaDB", category: "database" },
    CouchDB: { iconClass: "fas fa-database", label: "CouchDB", category: "database" },
    Cassandra: { iconClass: "fas fa-database", label: "Cassandra", category: "database" },
    DynamoDB: { iconClass: "fab fa-aws", label: "DynamoDB", category: "database" },
    Elasticsearch: { iconClass: "fas fa-search", label: "Elasticsearch", category: "database" },
    InfluxDB: { iconClass: "fas fa-chart-line", label: "InfluxDB", category: "database" },
    Neo4j: { iconClass: "fas fa-project-diagram", label: "Neo4j", category: "database" },
    Supabase: { iconClass: "fas fa-database", label: "Supabase", category: "database" },
    PlanetScale: { iconClass: "fas fa-globe", label: "PlanetScale", category: "database" },
    Prisma: { iconClass: "fas fa-prism", label: "Prisma", category: "database" },

    // --- Cloud & Backend Services ---
    Firebase: { iconClass: "fas fa-fire", label: "Firebase", category: "cloud" },
    Appwrite: { iconClass: "fas fa-cloud", label: "Appwrite", category: "cloud" },
    AWS: { iconClass: "fab fa-aws", label: "AWS", category: "cloud" },
    "Google Cloud": { iconClass: "fab fa-google", label: "Google Cloud", category: "cloud" },
    Azure: { iconClass: "fab fa-microsoft", label: "Azure", category: "cloud" },
    Heroku: { iconClass: "fas fa-cloud", label: "Heroku", category: "cloud" },
    Railway: { iconClass: "fas fa-train", label: "Railway", category: "cloud" },
    Render: { iconClass: "fas fa-cloud", label: "Render", category: "cloud" },
    DigitalOcean: { iconClass: "fas fa-water", label: "DigitalOcean", category: "cloud" },
    Linode: { iconClass: "fas fa-server", label: "Linode", category: "cloud" },
    Vultr: { iconClass: "fas fa-server", label: "Vultr", category: "cloud" },
    Convex: { iconClass: "fas fa-shapes", label: "Convex", category: "cloud" },
    Sanity: { iconClass: "fas fa-leaf", label: "Sanity", category: "cloud" },
    Strapi: { iconClass: "fas fa-server", label: "Strapi", category: "cloud" },
    Contentful: { iconClass: "fas fa-file-alt", label: "Contentful", category: "cloud" },

    // --- DevOps & Deployment ---
    Docker: { iconClass: "fab fa-docker", label: "Docker", category: "tool" },
    Kubernetes: { iconClass: "fas fa-dharmachakra", label: "Kubernetes", category: "tool" },
    Unraid: { iconClass: "fas fa-server", label: "Unraid", category: "tool" },
    Proxmox: { iconClass: "fas fa-server", label: "Proxmox", category: "tool" },
    NGINX: { iconClass: "fas fa-network-wired", label: "NGINX", category: "tool" },
    Apache: { iconClass: "fas fa-feather-alt", label: "Apache", category: "tool" },
    Caddy: { iconClass: "fas fa-server", label: "Caddy", category: "tool" },
    Traefik: { iconClass: "fas fa-route", label: "Traefik", category: "tool" },
    Vercel: { iconClass: "fas fa-triangle", label: "Vercel", category: "cloud" },
    Netlify: { iconClass: "fas fa-cloud-upload-alt", label: "Netlify", category: "cloud" },
    Cloudflare: { iconClass: "fas fa-cloud", label: "Cloudflare", category: "cloud" },
    "GitHub Actions": { iconClass: "fab fa-github", label: "GitHub Actions", category: "tool" },
    "GitLab CI": { iconClass: "fab fa-gitlab", label: "GitLab CI", category: "tool" },
    Jenkins: { iconClass: "fas fa-cogs", label: "Jenkins", category: "tool" },
    CircleCI: { iconClass: "fas fa-circle", label: "CircleCI", category: "tool" },
    "Travis CI": { iconClass: "fas fa-check", label: "Travis CI", category: "tool" },
    Terraform: { iconClass: "fas fa-layer-group", label: "Terraform", category: "tool" },
    Ansible: { iconClass: "fas fa-cogs", label: "Ansible", category: "tool" },
    Vagrant: { iconClass: "fas fa-box", label: "Vagrant", category: "tool" },

    // --- Version Control & Collaboration ---
    Git: { iconClass: "fab fa-git-alt", label: "Git", category: "tool" },
    GitHub: { iconClass: "fab fa-github", label: "GitHub", category: "tool" },
    GitLab: { iconClass: "fab fa-gitlab", label: "GitLab", category: "tool" },
    Bitbucket: { iconClass: "fab fa-bitbucket", label: "Bitbucket", category: "tool" },
    SVN: { iconClass: "fas fa-code-branch", label: "SVN", category: "tool" },

    // --- Build Tools & Bundlers ---
    Webpack: { iconClass: "fas fa-box-open", label: "Webpack", category: "tool" },
    Vite: { iconClass: "fas fa-bolt", label: "Vite", category: "tool" },
    Rollup: { iconClass: "fas fa-scroll", label: "Rollup", category: "tool" },
    Parcel: { iconClass: "fas fa-package", label: "Parcel", category: "tool" },
    esbuild: { iconClass: "fas fa-rocket", label: "esbuild", category: "tool" },
    Turbopack: { iconClass: "fas fa-bolt", label: "Turbopack", category: "tool" },
    Gulp: { iconClass: "fas fa-stream", label: "Gulp", category: "tool" },
    Grunt: { iconClass: "fas fa-hammer", label: "Grunt", category: "tool" },
    Babel: { iconClass: "fas fa-language", label: "Babel", category: "tool" },
    ESLint: { iconClass: "fas fa-check-circle", label: "ESLint", category: "tool" },
    Prettier: { iconClass: "fas fa-magic", label: "Prettier", category: "tool" },

    // --- Testing ---
    Jest: { iconClass: "fas fa-vial", label: "Jest", category: "tool" },
    Vitest: { iconClass: "fas fa-vial", label: "Vitest", category: "tool" },
    Cypress: { iconClass: "fas fa-check-circle", label: "Cypress", category: "tool" },
    Playwright: { iconClass: "fas fa-theater-masks", label: "Playwright", category: "tool" },
    Selenium: { iconClass: "fas fa-robot", label: "Selenium", category: "tool" },
    "Testing Library": { iconClass: "fas fa-flask", label: "Testing Library", category: "tool" },
    Mocha: { iconClass: "fas fa-coffee", label: "Mocha", category: "tool" },
    Chai: { iconClass: "fas fa-tea", label: "Chai", category: "tool" },
    Jasmine: { iconClass: "fas fa-flower", label: "Jasmine", category: "tool" },
    Puppeteer: { iconClass: "fas fa-dog", label: "Puppeteer", category: "tool" },

    // --- APIs & Communication ---
    "REST API": { iconClass: "fas fa-exchange-alt", label: "REST API", category: "other" },
    GraphQL: { iconClass: "fas fa-project-diagram", label: "GraphQL", category: "other" },
    WebSockets: { iconClass: "fas fa-bolt", label: "WebSockets", category: "other" },
    "Socket.io": { iconClass: "fas fa-plug", label: "Socket.io", category: "other" },
    gRPC: { iconClass: "fas fa-network-wired", label: "gRPC", category: "other" },
    tRPC: { iconClass: "fas fa-route", label: "tRPC", category: "other" },
    Apollo: { iconClass: "fas fa-rocket", label: "Apollo", category: "other" },
    Relay: { iconClass: "fas fa-satellite", label: "Relay", category: "other" },
    OAuth2: { iconClass: "fas fa-key", label: "OAuth2", category: "other" },
    JWT: { iconClass: "fas fa-user-lock", label: "JWT", category: "other" },
    Auth0: { iconClass: "fas fa-shield-alt", label: "Auth0", category: "other" },
    Clerk: { iconClass: "fas fa-user-shield", label: "Clerk", category: "other" },
    NextAuth: { iconClass: "fas fa-lock", label: "NextAuth", category: "other" },

    // --- Web APIs & Browser Features ---
    WebSpeechAPI: { iconClass: "fas fa-microphone-alt", label: "WebSpeechAPI", category: "other" },
    WebRTC: { iconClass: "fas fa-video", label: "WebRTC", category: "other" },
    "Service Workers": { iconClass: "fas fa-cog", label: "Service Workers", category: "other" },
    PWA: { iconClass: "fas fa-mobile-alt", label: "PWA", category: "other" },
    WebAssembly: { iconClass: "fas fa-cube", label: "WebAssembly", category: "other" },
    IndexedDB: { iconClass: "fas fa-database", label: "IndexedDB", category: "other" },
    "Local Storage": { iconClass: "fas fa-save", label: "Local Storage", category: "other" },
    Geolocation: { iconClass: "fas fa-map-marker-alt", label: "Geolocation", category: "other" },

    // --- AI & Machine Learning ---
    LangChain: { iconClass: "fas fa-robot", label: "LangChain", category: "other" },
    OpenAI: { iconClass: "fas fa-brain", label: "OpenAI", category: "other" },
    TensorFlow: { iconClass: "fas fa-brain", label: "TensorFlow", category: "other" },
    PyTorch: { iconClass: "fas fa-brain", label: "PyTorch", category: "other" },
    Keras: { iconClass: "fas fa-brain", label: "Keras", category: "other" },
    "Scikit-learn": { iconClass: "fas fa-chart-line", label: "Scikit-learn", category: "other" },
    Pandas: { iconClass: "fas fa-table", label: "Pandas", category: "other" },
    NumPy: { iconClass: "fas fa-calculator", label: "NumPy", category: "other" },
    Jupyter: { iconClass: "fas fa-book", label: "Jupyter", category: "other" },
    "Hugging Face": { iconClass: "fas fa-smile", label: "Hugging Face", category: "other" },
    Ollama: { iconClass: "fas fa-llama", label: "Ollama", category: "other" },
    Anthropic: { iconClass: "fas fa-robot", label: "Anthropic", category: "other" },

    // --- Data & Analytics ---
    "Apache Spark": { iconClass: "fas fa-fire", label: "Apache Spark", category: "other" },
    Hadoop: { iconClass: "fas fa-elephant", label: "Hadoop", category: "other" },
    Kafka: { iconClass: "fas fa-stream", label: "Kafka", category: "other" },
    RabbitMQ: { iconClass: "fas fa-rabbit", label: "RabbitMQ", category: "other" },
    Tableau: { iconClass: "fas fa-chart-bar", label: "Tableau", category: "other" },
    "Power BI": { iconClass: "fas fa-chart-pie", label: "Power BI", category: "other" },
    "D3.js": { iconClass: "fas fa-chart-area", label: "D3.js", category: "other" },
    "Chart.js": { iconClass: "fas fa-chart-bar", label: "Chart.js", category: "other" },

    // --- Automation & Scheduling ---
    Cron: { iconClass: "fas fa-clock", label: "Cron", category: "other" },
    "CI/CD": { iconClass: "fas fa-cogs", label: "CI/CD", category: "other" },
    Zapier: { iconClass: "fas fa-bolt", label: "Zapier", category: "other" },
    IFTTT: { iconClass: "fas fa-link", label: "IFTTT", category: "other" },
    n8n: { iconClass: "fas fa-project-diagram", label: "n8n", category: "other" },

    // --- CMS & Content ---
    WordPress: { iconClass: "fab fa-wordpress", label: "WordPress", category: "tool" },
    Drupal: { iconClass: "fab fa-drupal", label: "Drupal", category: "tool" },
    Ghost: { iconClass: "fas fa-ghost", label: "Ghost", category: "tool" },
    Notion: { iconClass: "fas fa-sticky-note", label: "Notion", category: "tool" },
    Airtable: { iconClass: "fas fa-table", label: "Airtable", category: "tool" },

    // --- Communication & APIs ---
    "Discord API": { iconClass: "fab fa-discord", label: "Discord API", category: "other" },
    "Slack API": { iconClass: "fab fa-slack", label: "Slack API", category: "other" },
    "Telegram API": { iconClass: "fas fa-paper-plane", label: "Telegram API", category: "other" },
    "WhatsApp API": { iconClass: "fab fa-whatsapp", label: "WhatsApp API", category: "other" },
    Twilio: { iconClass: "fas fa-phone", label: "Twilio", category: "other" },
    SendGrid: { iconClass: "fas fa-envelope", label: "SendGrid", category: "other" },
    Mailgun: { iconClass: "fas fa-mail-bulk", label: "Mailgun", category: "other" },

    // --- Monitoring & Analytics ---
    "Google Analytics": { iconClass: "fab fa-google", label: "Google Analytics", category: "other" },
    Mixpanel: { iconClass: "fas fa-chart-line", label: "Mixpanel", category: "other" },
    Amplitude: { iconClass: "fas fa-wave-square", label: "Amplitude", category: "other" },
    Sentry: { iconClass: "fas fa-bug", label: "Sentry", category: "other" },
    LogRocket: { iconClass: "fas fa-video", label: "LogRocket", category: "other" },
    Datadog: { iconClass: "fas fa-dog", label: "Datadog", category: "other" },
    "New Relic": { iconClass: "fas fa-chart-line", label: "New Relic", category: "other" },

    // --- E-commerce & Payments ---
    Stripe: { iconClass: "fab fa-stripe", label: "Stripe", category: "other" },
    PayPal: { iconClass: "fab fa-paypal", label: "PayPal", category: "other" },
    Shopify: { iconClass: "fab fa-shopify", label: "Shopify", category: "other" },
    WooCommerce: { iconClass: "fab fa-wordpress", label: "WooCommerce", category: "other" },
    Square: { iconClass: "fas fa-square", label: "Square", category: "other" },

    // --- General Skills & Concepts ---
    "Full-Stack": { iconClass: "fas fa-code", label: "Full-Stack", category: "other" },
    Frontend: { iconClass: "fas fa-desktop", label: "Frontend", category: "other" },
    Backend: { iconClass: "fas fa-server", label: "Backend", category: "other" },
    DevOps: { iconClass: "fas fa-cogs", label: "DevOps", category: "other" },
    "UI/UX": { iconClass: "fas fa-paint-brush", label: "UI/UX", category: "other" },
    "Responsive Design": { iconClass: "fas fa-mobile-alt", label: "Responsive Design", category: "other" },
    Accessibility: { iconClass: "fas fa-universal-access", label: "Accessibility", category: "other" },
    SEO: { iconClass: "fas fa-search", label: "SEO", category: "other" },
    Performance: { iconClass: "fas fa-tachometer-alt", label: "Performance", category: "other" },
    Security: { iconClass: "fas fa-shield-alt", label: "Security", category: "other" },
    Microservices: { iconClass: "fas fa-cubes", label: "Microservices", category: "other" },
    Serverless: { iconClass: "fas fa-cloud", label: "Serverless", category: "other" },
    "AI & ML": { iconClass: "fas fa-robot", label: "AI & ML", category: "other" },
    "Data Science": { iconClass: "fas fa-chart-line", label: "Data Science", category: "other" },
    "Project Management": { iconClass: "fas fa-tasks", label: "Project Management", category: "other" },
    Agile: { iconClass: "fas fa-sync", label: "Agile", category: "other" },
    Scrum: { iconClass: "fas fa-users", label: "Scrum", category: "other" },
    RAID: { iconClass: "fas fa-hdd", label: "RAID", category: "other" },

    // --- Fallback Icon ---
    default: { iconClass: "fas fa-code", label: "Skill", category: "other" },
};

export const getIcon = (key: string): string => TECH_STACK[key]?.iconClass || TECH_STACK["default"].iconClass;
